<!DOCTYPE html>
<html lang="en">
<head>
    <title>Halton Village Energy Project - About</title>
    <?php include('include/head.php'); ?>
</head>
<body>
    <?php include('include/navbar.php'); ?>
    <div class="wrapper">
        <div id="carousel-1" class="carousel slide dark-bg" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-1" data-slide-to="1"></li>
            <li data-target="#carousel-1" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active">
              <img src="img/c1.jpg" alt="Image 1">
            </div>
            <div class="item">
              <img src="img/c2.jpg" alt="Image 2">
            </div>
            <div class="item">
              <img src="img/c3.jpg" alt="Image 3">
            </div>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-1" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#carousel-1" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-10 box">
                    <h2>About the village</h2>
                    <p>The cohousing in Halton abides by and promotes ecological values. They aim at going green and helping save the environment. It has a set of residences with common launderette, dining area etc. They use these common areas so that they can socialize and make sure that they limit their energy consumption. All the houses have a set of solar panels and the electricity generated by these panels is being used for day-to-day purposes. They are even working on the Hydro Project. Each house does not have a personal heater or a geyser. So for heating, they use Bio Mass techniques. They have one big biomass heater which heats water and pumps it underneath the houses using pipes. There are houses which have cool roof techniques which helps the houses remain cool under a lot of sunlight.</p>

                    <h2>The problem</h2>
                    <p>There are some roadblocks which come in the way. Though each house has a personal meter and there is a common meter too, the users do not have a dedicated and en easy way to check the electricity generated and consumption statistics. This creates a problem for the residents because they do not know when there is electricity left to use and when there is a shortage of electricity. There are times in summers when they have to sell the electricity generated because there is excess of generation and there is no way that they can store it. In winters, there is a shortage of electricity and they have to buy the electricity. They need to get over these issues and understand the electricity metrics. There is no way that they can do it. This is where we come in. We have taken up this project and we call it “The Halton Village Project”.</p>
                    <p>We aim at visualizing the electricity generation and consumption information in a way which is easily accessible and understandable. This would enable them to make smart choices about the appropriate amount of electricity to use and best times to use it.</p>
                </div>
                <?php
                    include('include/links.php');
                ?>
            </div>
        </div>
    </div>
    <?php 
        include('include/scripts.php');
    ?>
</body>
</html>